query Posts($userId: ID!, $limit: Int!, $offset: Int!) {
  user(userId: $userId) {
    posts(limit: $limit, offset: $offset) {
      items {
        id
        title
        body
        user {
          name
        }
        createdAt
        updatedAt
      }
    }
  }
}
